# Generated by Django 6.0 on 2026-01-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='drink',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='stock_quantity',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
